### ISSUE TITLE
Moving files across directories causes a delete on re-index

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/usep_gh_handler_app#1]
When a file is moved from one directory to the other in USEP, for ex, from metadata_only to transcribed, the file is deleted from the index. It is in git, but there is no trace of it in solr. 

An example to trace in the logs:
NY.NY.NYU.L.6 
This file was committed to git on Jan 19 at 12:23am.

**Comment by birkin** [comment]
- fixed in commit 376e6d0664ae251742199acca188aa9fafabb306.

- changed order to handle solr deletions first, _then_ additions/updates.
